// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwnsafwnykfplmmdbyde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bnNhZndueWtmcGxtbWRieWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzIwODMsImV4cCI6MjA2MzU0ODA4M30.oLrl3JFaO_GopWm29nyEUZIBqD3Dm3d7_MQ46yLlI08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);